language: node_js
dist: xenial
node_js: lts/*
sudo: true

addons:
  firefox: latest
  chrome: stable

# limit the Travis 'build on push' feature to master and dist branches only
branches:
  only:
   - master

install:
  - yarn install
  - yarn build

  # bundlesize
  - yarn global add bundlesize@^0.17.0
  - bundlesize -f dist/sweetalert2.all.min.js -s 16kB

  # prevent adding devDependencies with a shitload of subdependencies
  - if [ `yarn list | wc -l` -gt 4000 ]; then
      exit 1;
    fi

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      yarn run check &&
      yarn add --dev jest &&
      yarn run check:jest;
    fi;

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      travis_retry yarn check:sauce &&
      yarn check:third-party;
    fi;

notifications:
  email:
    on_success: never

after_success:
  # run automated release process with semantic-release
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      yarn global add semantic-release@16.0.0-beta.18 @semantic-release/changelog@3 @semantic-release/exec@3.4.0-beta.2 @semantic-release/git@7.1.0-beta.3;
      semantic-release;
    fi;

  # report coverage to coveralls.io
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      yarn global add coveralls@3 &&
      cat ./coverage/lcov.info | coveralls;
    fi;
